version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend && npm install && npm install --save-dev codecov
            - run: cd backend && npm run citest
            - run: cd react-native-frontend && npm install && npm install --save-dev codecov jest@26.4.1
            - run: cd react-native-frontend && npm run citest
            - run: ssh -o 'StrictHostKeyChecking no' -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"
workflows:
    build-and-test:
      jobs:
        - build-and-test